### PR TITLE
Add extract_last_result decorator

### PR DESCRIPTION
**Pull request by aguilerapy**

### CODE REVIEW

**Review by romifz — APPROVED** [review]

**Comment by aguilerapy** [comment]
Do you know why the test failed here? @jpmckinney

**Comment by jpmckinney** [comment]
@aguilerapy I changed the tests in standard-maintenance-scripts, but the CI is using a cached version of OCDS Kit. I changed the requirements in standard-maintenance-scripts, so it should pass now.

**Comment by jpmckinney** [comment]
Aha, Toucan pins to an older version of OCDS Kit, so I had to update it here, too.

**Comment by aguilerapy** [comment]
Great! Thanks! @jpmckinney

**Pull request merged**
